### ISSUE TITLE
Pressing Start on PyTarkBot Crashes both PyTark and EFT

### ISSUE THREAD

**Issue by MFGAVIN** [matthewmiglio/py-TarkBot#2] opened 2022-08-24 22:04 UTC
I have Windows 11 and whenever I tried starting the tool it would crash the program and the game, what am I doing wrong?  I tried doing it with administrator too.
https://imgur.com/opy3A76

**Comment by matthewmiglio** [comment] 2022-08-24 22:11
Have you set the configuration file's launcher path to your launcher's location? 
This file is automatically created at appdata/roaming/py-TarkBot/config.json.
Make sure the directory path uses \\

The graphics setting path can be ignored.

**Comment by MFGAVIN** [comment] 2022-08-24 22:15
> Have you set the configuration file's launcher path to your launcher's location? This file is automatically created at appdata/roaming/py-TarkBot/config.json. Make sure the directory path uses \

Ok I'll fix it but to make sure it's suppose to have two \\ for the file paths? Because when I went to check it out I saw this

![notepad++_pOnKEW37lV](https://user-images.githubusercontent.com/40813002/186533107-c6ec6e48-32c4-42d8-abf5-2960f7eb93ad.png)

**Comment by MFGAVIN** [comment] 2022-08-24 22:24
Alright I've been messing with it a little bit and now it's at least giving me an error of [WinError 5] Access is denied

**Comment by matthewmiglio** [comment] 2022-08-24 22:40
Access is denied error is caused by the EFT denying the window resize method from changing the res. Theoretically, this is the issue that running in administrator mode fixes. Let me know if this issue specifically persists.

**Comment by MFGAVIN** [comment] 2022-08-24 22:47
> Access is denied error is caused by the EFT denying the window resize method from changing the res. Theoretically, this is the issue that running in administrator mode fixes. Let me know if this issue specifically persists.

Nah I fixed it, the issue was me not setting the BsgLauncher.exe last part for launcher_path and after I started it from fixing it actually launched but I encountered another issue stopping me 
![NVIDIA_Share_yekeBGYfTF](https://user-images.githubusercontent.com/40813002/186536735-15e34940-14ff-4859-bd5a-f97cb5f6f2e3.jpg)
but maybe I should start another issue for this since the first issue at hand was fixed (ty)

**Comment by matthewmiglio** [comment] 2022-08-24 22:49
would you tell me your monitor's resolution?

**Comment by MFGAVIN** [comment] 2022-08-24 22:50
1920x1080p, I'll double check the EFT resolution, could it also have something to do with Windows 11 and rounded edges or maybe I have a second monitor to the left as well.

**Comment by matthewmiglio** [comment] 2022-08-24 22:53
The bot should work normally on multi-monitor setups. Is the window automatically moving to the topleft? If so, the rounded edges are no problem. 

The issue you're seeing is caused by the program warning that it will move the mouse off (or too near) the edge, which I will have to code in a handle for.

Let me know if the tarkov client window moves automatically or not.

**Comment by matthewmiglio** [comment] 2022-08-24 22:55
Version 0.0.31 is out and should handle the error you had shown.

**Comment by MFGAVIN** [comment] 2022-08-24 22:58
Alright I'll check it out in a second I'm being forced to play some valorant.

**Comment by MFGAVIN** [comment] 2022-08-24 23:54
> Version 0.0.31 is out and should handle the error you had shown.

![mpc-hc64_NRyJKIIBWO](https://user-images.githubusercontent.com/40813002/186543985-5d42e477-3b2b-49fa-a1a7-2c03d9641d4d.png)
I'm getting this error when trying to start it, i'm going to uninstall and try again with 0.03.0 and again with 0.0.3.1

**Comment by MFGAVIN** [comment] 2022-08-25 00:23
Yeah I tried uninstalling and stuff and it still didn't work, I was able to install 0.0.3.0 and it got to the flea market selling point but wasn't able to actually sell anything sadly.

**Comment by matthewmiglio** [comment] 2022-08-25 00:37
I haven't successfully ported the program onto another machine yet so I expected as much.

This is the next step in my agenda, so perhaps a reliable ubiquitous version will be available soon.

Thanks for your help so far

**Comment by MFGAVIN** [comment] 2022-08-25 00:40
All good this is a pretty smart and cool idea to create and I think it's got a lot of potential.

**Comment by matthewmiglio** [comment] 2022-08-25 13:55
I was able to get the latest version (0.0.38) working overnight on another windows 10 machine. Let me know if this version works for your windows 11 machine.

Keep in mind only the flea mode works.

Also, I had missed what you said about discord at first.
I'd be happy to communicate there if you think that'd be easier.

**Comment by matthewmiglio** [comment] 2022-08-27 15:05
Any issues posed in this thread should be handled. 

If you encounter another error please open another issue.

**Closed** 2022-08-27 15:07 UTC
